org member

diff --git a/lib/repo/main b/lib/repo/main
--- a/lib/repo/main
+++ b/lib/repo/main
@@ -11,12 +11,7 @@ subcmd:
     ls              "list repo of owner"
     info            "Show detailed information of repo"
     del             "Remove repo"
-    clear           "clear repo"
-    issue           "get repo issue"
-    release         "release"
-    review          "review repo"
 '
-    # new             "new repo client"
     param:run
 
     if [ -z "$PARAM_SUBCMD" ]; then
@@ -36,174 +31,93 @@ ___x_cmd_gh_repo_create() {
 type:
     access  =   private public
 option:
-    --access                "private,public"                <>:RepoVisibility=private
+    --access                "private,public"                <>:access=private
     --description           "description"                   <>=""
     --homepage              "homepage"                      <>=""
     --no_issues             "Provide issue"
     --no_wiki               "Provide wiki"
-    --no_comment            "Provide can_comment"
+    --no_projects            "Provide has_projects"
     --no_auto_init          "auto init README"
-    --sw                    "Optional facility"             <>=""   =,  wiki    -wiki   comment  -comment   issue -issue
     --gitignore_template    "Git Ignore"                    <>:Ignore=" "
     --license_template      "license"                       <>:License=" "
-    --paths                 "repo path"                     <>:URL=""
+    --team_id               "the id of the team that will be granted access to this repository"   <>=""
     #n                      "repo names"
 '
-
     param:run
 
-    local private
-    case "$access" in
-        public)     private=false ;;
-        private)    private=true ;;
-    esac
+    local private=true
+    [ "$access" = "public" ] && private=false
 
     local has_issues=true
     local has_wiki=true
-    local can_comment=true
+    local has_projects=true
     local auto_init=true
     [ -n "$no_issues" ] &&      has_issues=false
     [ -n "$no_wiki" ] &&        has_wiki=false
-    [ -n "$no_comment" ] &&     can_comment=false
+    [ -n "$no_projects" ] &&     has_projects=false
     [ -n "$no_auto_init" ] &&   auto_init=false
 
     [ $# -eq 0 ] && gh_log info "repo create name is null" && return
     local name
     for name in "$@"; do
         {
-            local data repo_id url repo_owner
-            data=$(___x_cmd_gh_post_json "/v5/user/repos" name="${name##*/}" description homepage has_issues has_wiki can_comment \
-            auto_init gitignore_template license_template path="$paths" private 2>/dev/null)
-            ___json_awk_get repo_id=.id url=.html_url repo_owner=.owner.login <<A
-            $data
-A
-            if [ -n "$repo_id" ];then
-                ui tf "true" "Creating repo $name success" "repo_id:$repo_id" "url:$url" "repo_owner:$repo_owner" 
-            else
-                gh_log error "Creating repo failure: $name. Code is $code. " 
+            ___x_cmd_gh_post_json "/user/repos" name="${name##*/}" 
+            code=$?
+            if [ $code -ne 0 ]; then
+                gh_log error "Creating repo failure: $name. Code is $code. "
+                return $code
             fi
         }
     done
 }
 
-# ORGANIZATION NAME
-# shellcheck disable=SC2154,SC2034
-
-# https://github.com/api/v5/swagger#/postV5OrgsOrgRepos
 ___x_cmd_gh_org_repo_create() {
-    # TODO: I don't know what does path means for an organization repo
-    # path is null default repo name as path
+# TODO:option lack
     param:scope     "github/$O"
     param:dsl       '
 type:
-    access  =   private public innerSource
+    access  =   private public internal
 option:
     --org                   "organization create repo"      <>:name
     --description           "description"                   <>=""
-    --access                "private,public,innerSource"    <>:RepoVisibility=private
     --homepage              "homepage"                      <>:URL=""
+    --access                "private,public"                <>:access=private
     --no_issues             "Provide issue"
+    --no_projects            "Provide has_projects"
     --no_wiki               "Provide wiki"
-    --no_comment            "Provide can_comment"
     --no_auto_init          "auto init README"
+    --is_template           "make this repo available as a template" <>:Bool=false
     --gitignore_template    "Git Ignore"                    <>:Ignore=""
     --license_template      "license"                       <>:License=""
-    --paths                  "repo path"                    <>:URL=""
+    --team_id               "the id of the team that will be granted access to this repository"   <>=""
     #n                      "repo names"
 '
     param:run
 
-
-    case "$access" in
-        private)        private=0 ;;
-        public)         private=1 ;;
-        innerSource)    private=2 ;;
-    esac
+    local private=true
+    [ "$access" = "public" ] && private=false
 
     local has_issues=true
     local has_wiki=true
-    local can_comment=true
+    local has_projects=true
     local auto_init=true
     [ -n "$no_issues" ] && has_issues=false
     [ -n "$no_wiki" ] && has_wiki=false
-    [ -n "$no_comment" ] && can_comment=false
+    [ -n "$no_projects" ] && has_projects=false
     [ -n "$no_auto_init" ] && auto_init=false
     # TODO:owner may be personal
     local name
     for name in "$@"; do
-        # name="$(___x_cmd_gh_param_normalize_repo "$name")"
-        # owner="$(echo "$name" | cut -d / -f 1)"
-        # name="$(echo "$name" | cut -d / -f 2)"
-        local resp
         {
-            ___x_cmd_gh_post_json "/v5/orgs/$org/repos" name description homepage has_issues has_wiki can_comment auto_init \
-             gitignore_template license_template path="$paths" public
+            ___x_cmd_gh_post_json "/orgs/$org/repos" name description homepage has_issues has_wiki has_projects auto_init  visibility="$access"\
+             gitignore_template license_template
             code=$?
             if [ $code -ne 0 ]; then
                 gh_log error "Creating repo failure: $name. Code is $code. "
-                # ___x_cmd_gh_resp_header "" >&2
                 return $code
             fi
         } 
     done
-}
-
-# https://github.com/api/v5/swagger#/postV5EnterprisesEnterpriseRepos
-# shellcheck disable=SC2154
-___x_cmd_gh_enterprise_repo_create() {
-    param:scope     "github/$O"
-    param:dsl       '
-type:
-    access  =               private public innerSource
-option:
-    --enterprise            "enterprise space address"          <>
-    --access                "private,public,innerSource"        <>:RepoVisibility=private
-    --description           "description"                       <>=""
-    --homepage              "homepage"                          <>:URL=""
-    --paths                 "repo path"                         <>:URL=""
-    --no_issues             "Provide issue"
-    --no_wiki               "Provide wiki"
-    --no_comment            "Provide can_comment"
-    --no_auto_init          "auto init README"
-    --outsourced            "Provide outsourced"
-    --gitignore_template    "Git Ignore"                        <>:Ignore=""
-    --license_template      "license"                           <>:License=""
-    --project_creator       "Provide project_creator"           <>:name=""
-    --members               "Provide members(name or email)"    <>=""
-'
-    param:run
-
-    case "$access" in
-        private)        private=0 ;;
-        public)         private=1 ;;
-        innerSource)    private=2 ;;
-    esac
-    local has_issues=true
-    local has_wiki=true
-    local can_comment=true
-    local auto_init=true
-    [ -n "$no_issues" ] && has_issues=false
-    [ -n "$no_wiki" ] && has_wiki=false
-    [ -n "$no_comment" ] && can_comment=false
-    [ -n "$no_auto_init" ] && auto_init=false
-
-    outsourced=${outsourced:-false}
-
-    # TODO
-    local name
-    for name in "$@"; do
-    {
-        ___x_cmd_gh_post_json "/v5/enterprises/${enterprise##*/}/repos" \
-            name description homepage has_issues can_comment auto_init \
-            gitignore_template license_template path="$paths" private enterprise outsourced project_creator members
-            code=$?
-            if [ $code -ne 0 ]; then
-                gh_log error "Creating repo failure: $name. Code is $code. "
-                return $code
-            fi
-        } | json_color
-    done
-    return 0
 }
 
 
@@ -211,8 +125,6 @@ option:
 # Section 5: List Repos TODO:
 ############################
 
-# gh repo list --access inner-source <owner>
-# gh enterprise repo list
 ___x_cmd_gh_repo_ls() {
     param:void
     local owner
@@ -246,11 +158,9 @@ options:
     param:run
 
     ___x_cmd_gh_param_init_owner_repo
-    ___x_cmd_gh_get "/v5/repos/${owner_repo}"
-    # ___x_cmd_gh_get "/v5/repos/${owner}/${repo}"
+    ___x_cmd_gh_get "/repos/${owner_repo}"
 }
 
-# https://github.com/api/v5/swagger#/deleteV5ReposOwnerRepo
 ___x_cmd_gh_repo_del() {
     param:scope     "github/$O"
     param:dsl       '
@@ -260,13 +170,14 @@ options:
     param:run
     local confirm
     confirm=$(ui select "text" "Are you sure you want to delete repo $*" "yes" "no")
-    [ "$confirm" = "no" ] && return
+    [ "$confirm" = "yes" ] && return
     local i
     for i in "$@"; do
         ___x_cmd_gh_param_normalize_repo "$i"
-        ___x_cmd_gh_delete "/v5/repos/$owner_repo" >/dev/null 
+        ___x_cmd_gh_delete "/repos/$owner_repo" >/dev/null 
         if [ $? -eq 0 ]; then
-            ui tf "true" "deleted repo $i"
+            gh_log info "deleted repo $i"
+            # ui tf "true" "deleted repo $i"
         else
             gh_log error "Code is $?. Deleting repo failure: $i. Probably because it desn't exists."
         fi
